export interface Eleve {
  id: string;
  createdAt: Date;
  updatedAt: Date;
  matricule: string;
  nom: string;
  prenom: string;
  sexe: string;
  datenais: string | null;
  lieunais: string | null;
  adresse: string | null;
  email: string | null;
  phone: string | null;
  photo: string | null;
  notes: Array<{
    id: string;
    eleveId: string;
    annee: string;
    trimestreId: string;
    ortho: number | null;
    production: number | null;
    vocabulaire: number | null;
    grammaire: number | null;
    lecture: number | null;
    conjugaison: number | null;
    ecriture: number | null;
    numeriques: number | null;
    mesures: number | null;
    geometrie: number | null;
    probleme: number | null;
    histoire: number | null;
    geographie: number | null;
    ist: number | null;
    vivreEnsemble: number | null;
    vivreMilieu: number | null;
    dessin: number | null;
    recitation: number | null;
    total: number | null;
    moyenne: number | null;
    rang: number | null;
  }>;
}
